### ISSUE TITLE
Develop a Product card

### ISSUE THREAD

**Issue by CoHarsh** [MSTC-DA-IICT/Hacktoberfest22-R-for-React#3]
Develop a card which will show all products and it's details.

you should take a JSON file as source file which will contain all the information about the products and
then fetch that file info to .js file and then work on it.

**Comment by KaptainCS3** [comment]
!assign

**Comment by Jam-Burger** [comment]
I would like to work on this issue

**Comment by Jam-Burger** [comment]
should I use images from the internet or like amazon or there will be copyright issues?

**Comment by CoHarsh** [comment]
@Jam-Burger yes you can use that images

**Comment by CoHarsh** [comment]
any Update @Jam-Burger  ?

**Comment by Jam-Burger** [comment]
> any Update @Jam-Burger ?

I have made a JSON file of 5 images and created a card template using them
I am now improving the design of it
the work will be done till today evening
