### ISSUE TITLE
Make a Product JSON file

### ISSUE THREAD

**Issue by CoHarsh** [MSTC-DA-IICT/Hacktoberfest22-R-for-React#5]
In this task you should make a JSON file which will contain all the information about the product including photo URL of that product.

The moto to create this JSON file is to act like a backend response like JSON format.

**Comment by KaptainCS3** [comment]
!assign

**Comment by Jam-Burger** [comment]
I have to make a product JSON too because I have been assigned to make a product card.
so can you assign me this issue too?
